[
{"authors":[{"cat":"Райан","id":119456},{"cat":"Пёстроглаз","id":289662},{"cat":"Лейси","id":489667}],"name":"Транзакция","stickers":["/img/stickers/transaction1/1.png","/img/stickers/transaction1/2.png","/img/stickers/transaction1/3.png","/img/stickers/transaction1/4.png","/img/stickers/transaction1/5.png","/img/stickers/transaction1/6.png","/img/stickers/transaction1/7.png","/img/stickers/transaction1/8.png","/img/stickers/transaction1/9.png","/img/stickers/transaction1/10.png","/img/stickers/transaction2/1.png","/img/stickers/transaction2/2.png","/img/stickers/transaction2/3.png","/img/stickers/transaction2/4.png","/img/stickers/transaction2/5.png","/img/stickers/transaction2/6.png","/img/stickers/transaction2/7.png","/img/stickers/transaction2/8.png","/img/stickers/transaction2/9.png","/img/stickers/transaction2/10.png","/img/stickers/transaction3/1.png","/img/stickers/transaction3/2.png","/img/stickers/transaction3/3.png","/img/stickers/transaction3/4.png","/img/stickers/transaction3/5.png","/img/stickers/transaction3/6.png","/img/stickers/transaction3/7.png","/img/stickers/transaction3/8.png","/img/stickers/transaction3/9.png","/img/stickers/transaction3/10.png","/img/stickers/transaction3/11.png"]},

{"authors":[{"cat":"Райан","id":119456},{"cat":"Пёстроглаз","id":289662},{"cat":"Лейси","id":489667}],"name":"Мурр","stickers":["/img/stickers/murr1/1.png","/img/stickers/murr1/2.png","/img/stickers/murr1/3.png","/img/stickers/murr1/4.png","/img/stickers/murr1/5.png","/img/stickers/murr1/6.png","/img/stickers/murr1/7.png","/img/stickers/murr1/8.png","/img/stickers/murr1/9.png","/img/stickers/murr1/10.png","/img/stickers/murr2/1.png","/img/stickers/murr2/2.png","/img/stickers/murr2/3.png","/img/stickers/murr2/4.png","/img/stickers/murr2/5.png","/img/stickers/murr2/6.png","/img/stickers/murr2/7.png","/img/stickers/murr2/8.png","/img/stickers/murr2/9.png","/img/stickers/murr2/10.png","/img/stickers/murr3/1.png","/img/stickers/murr3/2.png","/img/stickers/murr3/3.png","/img/stickers/murr3/4.png","/img/stickers/murr3/5.png","/img/stickers/murr3/6.png","/img/stickers/murr3/7.png","/img/stickers/murr3/8.png","/img/stickers/murr3/9.png","/img/stickers/murr3/10.png"]},

{"authors":[{"cat":"Райан","id":119456},{"cat":"Пёстроглаз","id":289662},{"cat":"Лейси","id":489667}],"name":"Системолап","stickers":["/img/stickers/sistempaw1/1.png","/img/stickers/sistempaw1/2.png","/img/stickers/sistempaw1/3.png","/img/stickers/sistempaw1/4.png","/img/stickers/sistempaw1/5.png","/img/stickers/sistempaw1/6.png","/img/stickers/sistempaw1/7.png","/img/stickers/sistempaw1/8.png","/img/stickers/sistempaw1/9.png","/img/stickers/sistempaw1/10.png","/img/stickers/sistempaw2/1.png","/img/stickers/sistempaw2/2.png","/img/stickers/sistempaw2/3.png","/img/stickers/sistempaw2/4.png","/img/stickers/sistempaw2/5.png","/img/stickers/sistempaw2/6.png","/img/stickers/sistempaw2/7.png","/img/stickers/sistempaw2/8.png","/img/stickers/sistempaw2/9.png","/img/stickers/sistempaw2/10.png","/img/stickers/sistempaw3/1.png","/img/stickers/sistempaw3/2.png","/img/stickers/sistempaw3/3.png","/img/stickers/sistempaw3/4.png","/img/stickers/sistempaw3/5.png","/img/stickers/sistempaw3/6.png","/img/stickers/sistempaw3/7.png","/img/stickers/sistempaw3/8.png","/img/stickers/sistempaw3/9.png","/img/stickers/sistempaw3/10.png"]},

{"authors":[{"cat":"Клёнохвост","id":217776},{"cat":"Бушующелапа","id":711388},{"cat":"Змеелов","id":330319}],"name":"Предводитель","stickers":["/img/stickers/leader1/1.png","/img/stickers/leader1/2.png","/img/stickers/leader1/3.png","/img/stickers/leader1/4.png","/img/stickers/leader1/5.png","/img/stickers/leader1/6.png","/img/stickers/leader1/7.png","/img/stickers/leader1/8.png","/img/stickers/leader1/9.png","/img/stickers/leader1/10.png","/img/stickers/leader1/11.png","/img/stickers/leader2/1.png","/img/stickers/leader2/2.png","/img/stickers/leader2/3.png","/img/stickers/leader2/4.png","/img/stickers/leader2/5.png","/img/stickers/leader2/6.png","/img/stickers/leader2/7.png","/img/stickers/leader2/8.png","/img/stickers/leader2/9.png","/img/stickers/leader2/10.png","/img/stickers/leader2/11.png","/img/stickers/leader3/1.png","/img/stickers/leader3/2.png","/img/stickers/leader3/3.png","/img/stickers/leader3/4.png","/img/stickers/leader3/5.png","/img/stickers/leader3/6.png","/img/stickers/leader3/7.png","/img/stickers/leader3/8.png","/img/stickers/leader3/9.png","/img/stickers/leader3/10.png","/img/stickers/leader3/11.png","/img/stickers/leader3/12.png"]},

{"authors":[{"cat":"Клёнохвост","id":217776},{"cat":"Бушующелапа","id":711388},{"cat":"Змеелов","id":330319}],"name":"Модератор","stickers":["/img/stickers/moder1/1.png","/img/stickers/moder1/2.png","/img/stickers/moder1/3.png","/img/stickers/moder1/4.png","/img/stickers/moder1/5.png","/img/stickers/moder1/6.png","/img/stickers/moder1/7.png","/img/stickers/moder1/8.png","/img/stickers/moder1/9.png","/img/stickers/moder1/10.png","/img/stickers/moder1/11.png","/img/stickers/moder2/1.png","/img/stickers/moder2/1.png","/img/stickers/moder2/1.png","/img/stickers/moder2/1.png","/img/stickers/moder2/1.png","/img/stickers/moder2/1.png","/img/stickers/moder2/1.png","/img/stickers/moder2/1.png","/img/stickers/moder2/1.png","/img/stickers/moder2/1.png","/img/stickers/moder2/1.png","/img/stickers/moder2/1.png","/img/stickers/moder3/1.png","/img/stickers/moder3/2.png","/img/stickers/moder3/3.png","/img/stickers/moder3/4.png","/img/stickers/moder3/5.png","/img/stickers/moder3/6.png","/img/stickers/moder3/7.png","/img/stickers/moder3/8.png","/img/stickers/moder3/9.png","/img/stickers/moder3/10.png","/img/stickers/moder3/11.png","/img/stickers/moder3/12.png"]},

{"authors":[{"cat":"Клёнохвост","id":217776},{"cat":"Бушующелапа","id":711388},{"cat":"Змеелов","id":330319}],"name":"Нуб","stickers":["/img/stickers/noob1/1.png","/img/stickers/noob1/2.png","/img/stickers/noob1/3.png","/img/stickers/noob1/4.png","/img/stickers/noob1/5.png","/img/stickers/noob1/6.png","/img/stickers/noob1/7.png","/img/stickers/noob1/8.png","/img/stickers/noob1/9.png","/img/stickers/noob1/10.png","/img/stickers/noob1/11.png","/img/stickers/noob2/1.png","/img/stickers/noob2/2.png","/img/stickers/noob2/3.png","/img/stickers/noob2/4.png","/img/stickers/noob2/5.png","/img/stickers/noob2/6.png","/img/stickers/noob2/7.png","/img/stickers/noob2/8.png","/img/stickers/noob2/9.png","/img/stickers/noob2/10.png","/img/stickers/noob2/11.png","/img/stickers/noob3/1.png","/img/stickers/noob3/2.png","/img/stickers/noob3/3.png","/img/stickers/noob3/4.png","/img/stickers/noob3/5.png","/img/stickers/noob3/6.png","/img/stickers/noob3/7.png","/img/stickers/noob3/8.png","/img/stickers/noob3/9.png","/img/stickers/noob3/10.png","/img/stickers/noob3/11.png","/img/stickers/noob3/12.png"]}, 

]
